version: '3'
services:
    app:
        container_name: app2
        build: .
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
        ports:
            - '3897:80'
        expose:
            - '3897'
        depends_on:
            - db
        links:
            - 'db:www.databasepostgres2.com'
    db:
        container_name: db2
        image: postgres:10.1
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '5451:5432'
        expose:
            - '5451'
        volumes:
            - ./db/:/docker-entrypoint-initdb.d
    cron:
        container_name: cron-container
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - app
        links:
            - 'app:www.appUsd.com'
