version: '3'
services:
    app:
        container_name: app
        build: .
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
        ports:
            - '3895:80'
        expose:
            - '3895'
        depends_on:
            - db
        links:
            - 'db:www.databasepostgres.com'
    db:
        image: postgres:10.1
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '5450:5432'
        expose:
            - '5450'
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d
